on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "CodigoFacil"
    steps:
      - name: Hola mundo
        run: echo "Hola mundo ${MY_ENV_VAR}" 
  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo 2
        run: echo "Hola mundo 2"

       

       